#!/usr/bin/env python3
"""Validate the generated Bybit Quantumult X rules and repository metadata."""

from __future__ import annotations

import re
import sys
from pathlib import Path

import update_bybit_quantumultx as updater


ROOT = Path(__file__).resolve().parents[1]
MAIN_RULE = ROOT / "rule" / "QuantumultX" / "Bybit" / "Bybit.list"
REGIONAL_RULE = ROOT / "rule" / "QuantumultX" / "Bybit" / "Bybit-Regional.list"
ROOT_README = ROOT / "README.md"
DETAIL_README = ROOT / "rule" / "QuantumultX" / "Bybit" / "README.md"

ALLOWED_TYPES = frozenset(updater.TYPE_ORDER)
HEADER_KEYS = (
    "HOST",
    "HOST-SUFFIX",
    "IP-CIDR",
    "IP6-CIDR",
    "TOTAL",
)

EXPECTED_TEXT_FILES = (
    ROOT / "README.md",
    ROOT / "LICENSE",
    ROOT / ".gitignore",
    ROOT / "data" / "bybit_manual_domains.txt",
    ROOT / "data" / "bybit_excluded_domains.txt",
    ROOT / "scripts" / "update_bybit_quantumultx.py",
    ROOT / "scripts" / "validate_bybit_rules.py",
    ROOT / "scripts" / "repository_identity.py",
    ROOT / "tests" / "test_bybit_rules.py",
    ROOT / ".github" / "workflows" / "update-bybit-quantumultx.yml",
    MAIN_RULE,
    REGIONAL_RULE,
    DETAIL_README,
)

SECRET_PATTERNS = (
    ("GitHub token", re.compile(r"\bgh(?:p|o|u|s|r)_[A-Za-z0-9]{20,}\b")),
    ("fine-grained GitHub token", re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}\b")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("private key", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    (
        "UUID-like credential",
        re.compile(
            r"\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-"
            r"[89ab][0-9a-f]{3}-[0-9a-f]{12}\b",
            re.IGNORECASE,
        ),
    ),
)


def decode_utf8(path: Path, errors: list[str]) -> str:
    if not path.is_file():
        errors.append(f"{path.relative_to(ROOT)}: file does not exist")
        return ""
    try:
        return path.read_bytes().decode("utf-8")
    except UnicodeDecodeError as exc:
        errors.append(f"{path.relative_to(ROOT)}: not valid UTF-8: {exc}")
        return ""


def parse_header(text: str, path: Path, errors: list[str]) -> dict[str, int]:
    values: dict[str, int] = {}
    for key in HEADER_KEYS:
        match = re.search(rf"^# {re.escape(key)}:\s*(\d+)\s*$", text, re.MULTILINE)
        if not match:
            errors.append(f"{path.relative_to(ROOT)}: missing header count {key}")
            continue
        values[key] = int(match.group(1))
    return values


def validate_rule_file(path: Path, *, minimum_rules: int = 1) -> tuple[list[updater.Rule], str, list[str]]:
    errors: list[str] = []
    text = decode_utf8(path, errors)
    if not text:
        return [], text, errors

    placeholder_patterns = (
        r"<(?:真实用户名|真实仓库名|USERNAME|REPOSITORY)>",
        r"\bYOUR[_ -]?(?:USERNAME|REPOSITORY)\b",
        r"\bYYYY-MM-DD\b",
        r"https?://(?:www\.)?example\.com",
    )
    for pattern in placeholder_patterns:
        if re.search(pattern, text, re.IGNORECASE):
            errors.append(f"{path.relative_to(ROOT)}: contains placeholder matching {pattern!r}")

    rules: list[updater.Rule] = []
    seen: dict[tuple[str, str], int] = {}
    raw_rule_lines: list[str] = []

    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        raw_rule_lines.append(line)
        parts = [part.strip() for part in line.split(",")]
        if len(parts) != 3:
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: expected exactly three columns"
            )
            continue
        kind, value, policy = parts
        if policy != "Bybit":
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: policy must be Bybit, got {policy!r}"
            )
        if kind not in ALLOWED_TYPES:
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: unsupported type {kind!r}"
            )
            continue
        if kind in {"DOMAIN", "DOMAIN-SUFFIX", "HOST-KEYWORD"}:
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: forbidden type {kind!r}"
            )
            continue
        try:
            rule = updater.make_rule(kind, value)
            updater.validate_rule_allowed(rule)
        except updater.SafetyError as exc:
            errors.append(f"{path.relative_to(ROOT)}:{line_number}: {exc}")
            continue
        if value != rule.value:
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: value is not canonical: "
                f"{value!r} should be {rule.value!r}"
            )
        key = (rule.kind, rule.value.casefold())
        if key in seen:
            errors.append(
                f"{path.relative_to(ROOT)}:{line_number}: duplicate of line {seen[key]}"
            )
        else:
            seen[key] = line_number
        rules.append(rule)

    if len(rules) < minimum_rules:
        errors.append(
            f"{path.relative_to(ROOT)}: only {len(rules)} rules; minimum is {minimum_rules}"
        )

    sorted_rules = updater.sort_rules(rules)
    if rules != sorted_rules:
        errors.append(f"{path.relative_to(ROOT)}: rules are not in canonical order")

    collapsed = updater.collapse_parent_coverage(rules)
    if rules != collapsed:
        original = {rule.qx_line() for rule in rules}
        reduced = {rule.qx_line() for rule in collapsed}
        redundant = sorted(original - reduced)
        errors.append(
            f"{path.relative_to(ROOT)}: parent HOST-SUFFIX coverage makes rules redundant: "
            + ", ".join(redundant)
        )

    header = parse_header(text, path, errors)
    counts = updater.count_rules(rules)
    for key in HEADER_KEYS:
        if key in header and header[key] != counts[key]:
            errors.append(
                f"{path.relative_to(ROOT)}: header {key}={header[key]}, "
                f"actual={counts[key]}"
            )

    if raw_rule_lines and any(
        re.match(r"^(?:DOMAIN|DOMAIN-SUFFIX|HOST-KEYWORD),", line, re.IGNORECASE)
        for line in raw_rule_lines
    ):
        errors.append(f"{path.relative_to(ROOT)}: contains a forbidden rule syntax")
    return rules, text, errors


def validate_readme_counts(
    path: Path,
    expected: dict[str, int],
    expected_updated: str,
) -> list[str]:
    errors: list[str] = []
    text = decode_utf8(path, errors)
    if not text:
        return errors
    pattern = re.compile(
        r"<!-- BYBIT_COUNTS_START -->(\d+) 条（HOST (\d+)，"
        r"HOST-SUFFIX (\d+)，IP-CIDR (\d+)，IP6-CIDR (\d+)）"
        r"<!-- BYBIT_COUNTS_END -->"
    )
    match = pattern.search(text)
    if not match:
        errors.append(f"{path.relative_to(ROOT)}: missing or invalid count marker")
    else:
        total, host, host_suffix, ipv4, ipv6 = map(int, match.groups())
        actual = {
            "TOTAL": total,
            "HOST": host,
            "HOST-SUFFIX": host_suffix,
            "IP-CIDR": ipv4,
            "IP6-CIDR": ipv6,
        }
        if actual != expected:
            errors.append(
                f"{path.relative_to(ROOT)}: README counts {actual} do not match {expected}"
            )

    if path == DETAIL_README:
        updated_match = re.search(
            r"<!-- BYBIT_UPDATED_START -->(.*?)<!-- BYBIT_UPDATED_END -->",
            text,
        )
        if not updated_match:
            errors.append(f"{path.relative_to(ROOT)}: missing update-time marker")
        elif updated_match.group(1) != expected_updated:
            errors.append(
                f"{path.relative_to(ROOT)}: update time "
                f"{updated_match.group(1)!r} does not match {expected_updated!r}"
            )
    return errors


def validate_no_secrets() -> list[str]:
    errors: list[str] = []
    for path in EXPECTED_TEXT_FILES:
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for label, pattern in SECRET_PATTERNS:
            if pattern.search(text):
                errors.append(
                    f"{path.relative_to(ROOT)}: contains a possible {label}"
                )
    return errors


def main() -> int:
    errors: list[str] = []
    main_rules, main_text, main_errors = validate_rule_file(
        MAIN_RULE,
        minimum_rules=8,
    )
    errors.extend(main_errors)

    _, _, regional_errors = validate_rule_file(REGIONAL_RULE, minimum_rules=1)
    errors.extend(regional_errors)

    if main_text:
        expected_counts = updater.count_rules(main_rules)
        updated = updater.extract_updated_at(main_text)
        if not updated:
            errors.append(f"{MAIN_RULE.relative_to(ROOT)}: missing UPDATED header")
            updated = ""
        for readme in (ROOT_README, DETAIL_README):
            errors.extend(validate_readme_counts(readme, expected_counts, updated))

        repo_match = re.search(r"^# REPO:\s*(\S+)\s*$", main_text, re.MULTILINE)
        if not repo_match or repo_match.group(1) != updater.REPOSITORY_URL:
            errors.append(
                f"{MAIN_RULE.relative_to(ROOT)}: REPO header must be "
                f"{updater.REPOSITORY_URL}"
            )

    errors.extend(validate_no_secrets())

    if errors:
        print(f"Validation failed with {len(errors)} error(s):", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    counts = updater.count_rules(main_rules)
    print(
        "Validation passed: "
        f"{counts['TOTAL']} main rules "
        f"(HOST={counts['HOST']}, HOST-SUFFIX={counts['HOST-SUFFIX']}, "
        f"IP-CIDR={counts['IP-CIDR']}, IP6-CIDR={counts['IP6-CIDR']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
